// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZd5IyP83F9ZexuOUKTPqGn-JQBXmpnJ4',
    appId: '1:1014896489487:android:4d41cc8a661d3e8ef25f7a',
    messagingSenderId: '1014896489487',
    projectId: 'family-map-1222c',
    databaseURL: 'https://family-map-1222c-default-rtdb.firebaseio.com',
    storageBucket: 'family-map-1222c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpB8uHWiff1aG4l_pWss_5QSb49i8mIpE',
    appId: '1:1014896489487:ios:a5784032768c92bdf25f7a',
    messagingSenderId: '1014896489487',
    projectId: 'family-map-1222c',
    databaseURL: 'https://family-map-1222c-default-rtdb.firebaseio.com',
    storageBucket: 'family-map-1222c.firebasestorage.app',
    iosBundleId: 'com.naylinhte.family-map',
  );
}
