# Keep CocoaPods and Flutter's generated Swift package on a platform supported
# by the Firebase iOS SDK used by this app.
platform :ios, '15.0'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner

  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
